//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCompose.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCompose.i18n.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCompose.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep on invalid sequences.
        /// </summary>
        public static string BeepOnInvalid {
            get {
                return ResourceManager.GetString("BeepOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall back to case insensitive matches on invalid sequences.
        /// </summary>
        public static string CaseInsensitive {
            get {
                return ResourceManager.GetString("CaseInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose Key:.
        /// </summary>
        public static string ComposeKey {
            get {
                return ResourceManager.GetString("ComposeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard characters from invalid sequences.
        /// </summary>
        public static string DiscardOnInvalid {
            get {
                return ResourceManager.GetString("DiscardOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate CapsLock using both Shift keys.
        /// </summary>
        public static string EmulateCapsLock {
            get {
                return ResourceManager.GetString("EmulateCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In selected categories.
        /// </summary>
        public static string InSelectedCategories {
            get {
                return ResourceManager.GetString("InSelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert zero-width spaces in Office apps.
        /// </summary>
        public static string InsertZwsp {
            get {
                return ResourceManager.GetString("InsertZwsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain original compose key behaviour.
        /// </summary>
        public static string KeepOriginalKey {
            get {
                return ResourceManager.GetString("KeepOriginalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string KeyApps {
            get {
                return ResourceManager.GetString("KeyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        public static string KeyCapital {
            get {
                return ResourceManager.GetString("KeyCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Control.
        /// </summary>
        public static string KeyLControl {
            get {
                return ResourceManager.GetString("KeyLControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Alt.
        /// </summary>
        public static string KeyLMenu {
            get {
                return ResourceManager.GetString("KeyLMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Windows.
        /// </summary>
        public static string KeyLWin {
            get {
                return ResourceManager.GetString("KeyLWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Lock.
        /// </summary>
        public static string KeyNumLock {
            get {
                return ResourceManager.GetString("KeyNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string KeyPause {
            get {
                return ResourceManager.GetString("KeyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Control.
        /// </summary>
        public static string KeyRControl {
            get {
                return ResourceManager.GetString("KeyRControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Alt.
        /// </summary>
        public static string KeyRMenu {
            get {
                return ResourceManager.GetString("KeyRMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Windows.
        /// </summary>
        public static string KeyRWin {
            get {
                return ResourceManager.GetString("KeyRWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Lock.
        /// </summary>
        public static string KeyScroll {
            get {
                return ResourceManager.GetString("KeyScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded @1@ Sequences.
        /// </summary>
        public static string Obsolete001 {
            get {
                return ResourceManager.GetString("Obsolete001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose Key is @1@.
        /// </summary>
        public static string Obsolete002 {
            get {
                return ResourceManager.GetString("Obsolete002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetect.
        /// </summary>
        public static string Obsolete003 {
            get {
                return ResourceManager.GetString("Obsolete003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grave Accent `.
        /// </summary>
        public static string Obsolete016 {
            get {
                return ResourceManager.GetString("Obsolete016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 milliseconds.
        /// </summary>
        public static string Obsolete017 {
            get {
                return ResourceManager.GetString("Obsolete017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 second.
        /// </summary>
        public static string Obsolete018 {
            get {
                return ResourceManager.GetString("Obsolete018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 seconds.
        /// </summary>
        public static string Obsolete019 {
            get {
                return ResourceManager.GetString("Obsolete019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 seconds.
        /// </summary>
        public static string Obsolete020 {
            get {
                return ResourceManager.GetString("Obsolete020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 seconds.
        /// </summary>
        public static string Obsolete021 {
            get {
                return ResourceManager.GetString("Obsolete021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 seconds.
        /// </summary>
        public static string Obsolete022 {
            get {
                return ResourceManager.GetString("Obsolete022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Obsolete023 {
            get {
                return ResourceManager.GetString("Obsolete023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Obsolete025 {
            get {
                return ResourceManager.GetString("Obsolete025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Obsolete026 {
            get {
                return ResourceManager.GetString("Obsolete026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;History.
        /// </summary>
        public static string Obsolete027 {
            get {
                return ResourceManager.GetString("Obsolete027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey &amp;List.
        /// </summary>
        public static string Obsolete028 {
            get {
                return ResourceManager.GetString("Obsolete028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options….
        /// </summary>
        public static string Obsolete029 {
            get {
                return ResourceManager.GetString("Obsolete029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        public static string Obsolete030 {
            get {
                return ResourceManager.GetString("Obsolete030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Visit Website.
        /// </summary>
        public static string Obsolete031 {
            get {
                return ResourceManager.GetString("Obsolete031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@.
        /// </summary>
        public static string Obsolete033 {
            get {
                return ResourceManager.GetString("Obsolete033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ v@APP_VERSION@\n.
        /// </summary>
        public static string Obsolete034 {
            get {
                return ResourceManager.GetString("Obsolete034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        public static string Obsolete035 {
            get {
                return ResourceManager.GetString("Obsolete035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Sam Hocevar &lt;sam@hocevar.net&gt;\n.
        /// </summary>
        public static string Obsolete036 {
            get {
                return ResourceManager.GetString("Obsolete036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Obsolete038 {
            get {
                return ResourceManager.GetString("Obsolete038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Obsolete039 {
            get {
                return ResourceManager.GetString("Obsolete039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char.
        /// </summary>
        public static string Obsolete040 {
            get {
                return ResourceManager.GetString("Obsolete040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        public static string Obsolete041 {
            get {
                return ResourceManager.GetString("Obsolete041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Character.
        /// </summary>
        public static string Obsolete050 {
            get {
                return ResourceManager.GetString("Obsolete050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Obsolete051 {
            get {
                return ResourceManager.GetString("Obsolete051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ (disabled).
        /// </summary>
        public static string Obsolete052 {
            get {
                return ResourceManager.GetString("Obsolete052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ (active).
        /// </summary>
        public static string Obsolete053 {
            get {
                return ResourceManager.GetString("Obsolete053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ (typing).
        /// </summary>
        public static string Obsolete054 {
            get {
                return ResourceManager.GetString("Obsolete054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay:.
        /// </summary>
        public static string ResetDelay {
            get {
                return ResourceManager.GetString("ResetDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filter:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences.
        /// </summary>
        public static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift key disables CapsLock.
        /// </summary>
        public static string ShiftDisablesCapsLock {
            get {
                return ResourceManager.GetString("ShiftDisablesCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Sequences….
        /// </summary>
        public static string ShowSequences {
            get {
                return ResourceManager.GetString("ShowSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings….
        /// </summary>
        public static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCompose on {0} ({1} sequences).
        /// </summary>
        public static string TrayToolTip {
            get {
                return ResourceManager.GetString("TrayToolTip", resourceCulture);
            }
        }
    }
}
