//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCompose.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text_sc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text_sc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCompose.i18n.Text.sc", typeof(Text_sc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sona si una filera no est vàlida.
        /// </summary>
        public static string BeepOnInvalid {
            get {
                return ResourceManager.GetString("BeepOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesti sas fileras non vàlidas sena distinghimentu intre maiùscolas e minùscolas.
        /// </summary>
        public static string CaseInsensitive {
            get {
                return ResourceManager.GetString("CaseInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serra.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecla Compose:.
        /// </summary>
        public static string ComposeKey {
            get {
                return ResourceManager.GetString("ComposeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irbòlica sos caràteres de sas fileras non vàlidas.
        /// </summary>
        public static string DiscardOnInvalid {
            get {
                return ResourceManager.GetString("DiscardOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmulateCapsLock {
            get {
                return ResourceManager.GetString("EmulateCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Essi.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InSelectedCategories {
            get {
                return ResourceManager.GetString("InSelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InsertZwsp {
            get {
                return ResourceManager.GetString("InsertZwsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string KeepOriginalKey {
            get {
                return ResourceManager.GetString("KeepOriginalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menù.
        /// </summary>
        public static string KeyApps {
            get {
                return ResourceManager.GetString("KeyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc Maiusc.
        /// </summary>
        public static string KeyCapital {
            get {
                return ResourceManager.GetString("KeyCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl de manca.
        /// </summary>
        public static string KeyLControl {
            get {
                return ResourceManager.GetString("KeyLControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt de manca.
        /// </summary>
        public static string KeyLMenu {
            get {
                return ResourceManager.GetString("KeyLMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win de manca.
        /// </summary>
        public static string KeyLWin {
            get {
                return ResourceManager.GetString("KeyLWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc Num.
        /// </summary>
        public static string KeyNumLock {
            get {
                return ResourceManager.GetString("KeyNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausa.
        /// </summary>
        public static string KeyPause {
            get {
                return ResourceManager.GetString("KeyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl de destra.
        /// </summary>
        public static string KeyRControl {
            get {
                return ResourceManager.GetString("KeyRControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt de destra.
        /// </summary>
        public static string KeyRMenu {
            get {
                return ResourceManager.GetString("KeyRMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win de destra.
        /// </summary>
        public static string KeyRWin {
            get {
                return ResourceManager.GetString("KeyRWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc Scorr.
        /// </summary>
        public static string KeyScroll {
            get {
                return ResourceManager.GetString("KeyScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limba de s&apos;interfàtzia:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Mappings {
            get {
                return ResourceManager.GetString("Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @1@ fileras carrigadas.
        /// </summary>
        public static string Obsolete001 {
            get {
                return ResourceManager.GetString("Obsolete001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa tecla Compose est @1@.
        /// </summary>
        public static string Obsolete002 {
            get {
                return ResourceManager.GetString("Obsolete002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releva automaticamente.
        /// </summary>
        public static string Obsolete003 {
            get {
                return ResourceManager.GetString("Obsolete003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atzentu grave.
        /// </summary>
        public static string Obsolete016 {
            get {
                return ResourceManager.GetString("Obsolete016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 ms.
        /// </summary>
        public static string Obsolete017 {
            get {
                return ResourceManager.GetString("Obsolete017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 s.
        /// </summary>
        public static string Obsolete018 {
            get {
                return ResourceManager.GetString("Obsolete018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 s.
        /// </summary>
        public static string Obsolete019 {
            get {
                return ResourceManager.GetString("Obsolete019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 s.
        /// </summary>
        public static string Obsolete020 {
            get {
                return ResourceManager.GetString("Obsolete020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 s.
        /// </summary>
        public static string Obsolete021 {
            get {
                return ResourceManager.GetString("Obsolete021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 s.
        /// </summary>
        public static string Obsolete022 {
            get {
                return ResourceManager.GetString("Obsolete022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinita.
        /// </summary>
        public static string Obsolete023 {
            get {
                return ResourceManager.GetString("Obsolete023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabìlita.
        /// </summary>
        public static string Obsolete025 {
            get {
                return ResourceManager.GetString("Obsolete025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torra a aviare.
        /// </summary>
        public static string Obsolete026 {
            get {
                return ResourceManager.GetString("Obsolete026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Istòria.
        /// </summary>
        public static string Obsolete027 {
            get {
                return ResourceManager.GetString("Obsolete027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teclas lestras &amp;Lista.
        /// </summary>
        public static string Obsolete028 {
            get {
                return ResourceManager.GetString("Obsolete028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Optziones….
        /// </summary>
        public static string Obsolete029 {
            get {
                return ResourceManager.GetString("Obsolete029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Informatziones.
        /// </summary>
        public static string Obsolete030 {
            get {
                return ResourceManager.GetString("Obsolete030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bìsita su giassu/situ.
        /// </summary>
        public static string Obsolete031 {
            get {
                return ResourceManager.GetString("Obsolete031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@.
        /// </summary>
        public static string Obsolete033 {
            get {
                return ResourceManager.GetString("Obsolete033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ v@APP_VERSION@\n.
        /// </summary>
        public static string Obsolete034 {
            get {
                return ResourceManager.GetString("Obsolete034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        public static string Obsolete035 {
            get {
                return ResourceManager.GetString("Obsolete035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de Sam Hocevar &lt;sam@hocevar.net&gt;\n.
        /// </summary>
        public static string Obsolete036 {
            get {
                return ResourceManager.GetString("Obsolete036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optziones.
        /// </summary>
        public static string Obsolete038 {
            get {
                return ResourceManager.GetString("Obsolete038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filera.
        /// </summary>
        public static string Obsolete039 {
            get {
                return ResourceManager.GetString("Obsolete039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caràtere.
        /// </summary>
        public static string Obsolete040 {
            get {
                return ResourceManager.GetString("Obsolete040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        public static string Obsolete041 {
            get {
                return ResourceManager.GetString("Obsolete041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia caràtere.
        /// </summary>
        public static string Obsolete050 {
            get {
                return ResourceManager.GetString("Obsolete050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descritzione:.
        /// </summary>
        public static string Obsolete051 {
            get {
                return ResourceManager.GetString("Obsolete051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ (disabilitada).
        /// </summary>
        public static string Obsolete052 {
            get {
                return ResourceManager.GetString("Obsolete052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ (ativa).
        /// </summary>
        public static string Obsolete053 {
            get {
                return ResourceManager.GetString("Obsolete053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @APP_NAME@ (ses iscriende).
        /// </summary>
        public static string Obsolete054 {
            get {
                return ResourceManager.GetString("Obsolete054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durada ativatzione:.
        /// </summary>
        public static string ResetDelay {
            get {
                return ResourceManager.GetString("ResetDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chirca filtrada:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fileras.
        /// </summary>
        public static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShiftDisablesCapsLock {
            get {
                return ResourceManager.GetString("ShiftDisablesCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammustra &amp;Fileras….
        /// </summary>
        public static string ShowSequences {
            get {
                return ResourceManager.GetString("ShowSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TrayToolTip {
            get {
                return ResourceManager.GetString("TrayToolTip", resourceCulture);
            }
        }
    }
}
