//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCompose.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCompose.i18n.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WinCompose.
        /// </summary>
        public static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Injected Keys.
        /// </summary>
        public static string AllowInjected {
            get {
                return ResourceManager.GetString("AllowInjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ignore keys sent by other software like AutoHotkey or Synergy.
        /// </summary>
        public static string AllowInjectedToolTip {
            get {
                return ResourceManager.GetString("AllowInjectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate compose key is always Compose.
        /// </summary>
        public static string AlwaysCompose {
            get {
                return ResourceManager.GetString("AlwaysCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, all compose keys will be treated as Compose in a sequence. By default, only the first pressed key will act as Compose, and alternate compose keys will keep their original role..
        /// </summary>
        public static string AlwaysComposeToolTip {
            get {
                return ResourceManager.GetString("AlwaysComposeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetect.
        /// </summary>
        public static string AutodetectLanguage {
            get {
                return ResourceManager.GetString("AutodetectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch WinCompose on login.
        /// </summary>
        public static string AutoLaunch {
            get {
                return ResourceManager.GetString("AutoLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, WinCompose will be started when the user logs in..
        /// </summary>
        public static string AutoLaunchToolTip {
            get {
                return ResourceManager.GetString("AutoLaunchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emit a beep.
        /// </summary>
        public static string BeepOnInvalid {
            get {
                return ResourceManager.GetString("BeepOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the entered sequence does not exist, emit a system sound..
        /// </summary>
        public static string BeepOnInvalidToolTip {
            get {
                return ResourceManager.GetString("BeepOnInvalidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock always capitalizes letters.
        /// </summary>
        public static string CapsLockCapitalizes {
            get {
                return ResourceManager.GetString("CapsLockCapitalizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Caps Lock is on, typing an accented letter such as “é” will always output the corresponding capitalized letter, in this case “É”..
        /// </summary>
        public static string CapsLockCapitalizesToolTip {
            get {
                return ResourceManager.GetString("CapsLockCapitalizesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press a key to use as your compose key..
        /// </summary>
        public static string CaptureComposeKey {
            get {
                return ResourceManager.GetString("CaptureComposeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall back to case insensitive matches.
        /// </summary>
        public static string CaseInsensitive {
            get {
                return ResourceManager.GetString("CaseInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the entered sequence does not exist, but there is one that only differs by case, automatically correct it..
        /// </summary>
        public static string CaseInsensitiveToolTip {
            get {
                return ResourceManager.GetString("CaseInsensitiveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change….
        /// </summary>
        public static string ChangeComposeKey {
            get {
                return ResourceManager.GetString("ChangeComposeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, WinCompose will connect to the Internet at regular intervals to check for new versions. Updates are not installed automatically..
        /// </summary>
        public static string CheckUpdatesToolTip {
            get {
                return ResourceManager.GetString("CheckUpdatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose Key:.
        /// </summary>
        public static string ComposeKey {
            get {
                return ResourceManager.GetString("ComposeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the key that should act as the Compose key..
        /// </summary>
        public static string ComposeKeyToolTip {
            get {
                return ResourceManager.GetString("ComposeKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composing.
        /// </summary>
        public static string Composing {
            get {
                return ResourceManager.GetString("Composing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Window.
        /// </summary>
        public static string DebugWindow {
            get {
                return ResourceManager.GetString("DebugWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string DelaySeconds {
            get {
                return ResourceManager.GetString("DelaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCompose is disabled.
        /// </summary>
        public static string DisabledToolTip {
            get {
                return ResourceManager.GetString("DisabledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable notification area icon.
        /// </summary>
        public static string DisableIcon {
            get {
                return ResourceManager.GetString("DisableIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, WinCompose will no longer display an icon in the notification area. The only way to open the WinCompose interface will then be through the “WinCompose Settings” and “WinCompose Sequences” entries in the startup menu..
        /// </summary>
        public static string DisableIconToolTip {
            get {
                return ResourceManager.GetString("DisableIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all typed characters.
        /// </summary>
        public static string DiscardOnInvalid {
            get {
                return ResourceManager.GetString("DiscardOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the entered sequence does not exist, discard all the characters that were typed. The default behaviour is to output the characters as if the compose key had not been used..
        /// </summary>
        public static string DiscardOnInvalidToolTip {
            get {
                return ResourceManager.GetString("DiscardOnInvalidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Page.
        /// </summary>
        public static string DonationPage {
            get {
                return ResourceManager.GetString("DonationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download WinCompose {0}.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoji.
        /// </summary>
        public static string Emoji {
            get {
                return ResourceManager.GetString("Emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate Caps Lock using both Shift keys.
        /// </summary>
        public static string EmulateCapsLock {
            get {
                return ResourceManager.GetString("EmulateCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Caps Lock is used as the compose key, the original behaviour of the key becomes unavailable. This feature allows to turn Caps Lock on by pressing both Shift keys simultaneously..
        /// </summary>
        public static string EmulateCapsLockToolTip {
            get {
                return ResourceManager.GetString("EmulateCapsLockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore windows matching this regex:.
        /// </summary>
        public static string IgnoreRegex {
            get {
                return ResourceManager.GetString("IgnoreRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCompose will be completely disabled when the current window class or window name matches this regular expression..
        /// </summary>
        public static string IgnoreRegexToolTip {
            get {
                return ResourceManager.GetString("IgnoreRegexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In selected categories.
        /// </summary>
        public static string InSelectedCategories {
            get {
                return ResourceManager.GetString("InSelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert zero-width spaces in Office apps.
        /// </summary>
        public static string InsertZwsp {
            get {
                return ResourceManager.GetString("InsertZwsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office applications sometimes change the document font on the fly when entering certain Unicode characters. This feature inserts an invisible character after the Unicode character to work around the bug..
        /// </summary>
        public static string InsertZwspToolTip {
            get {
                return ResourceManager.GetString("InsertZwspToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On invalid sequences.
        /// </summary>
        public static string InvalidSequences {
            get {
                return ResourceManager.GetString("InvalidSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep notification area icon always visible.
        /// </summary>
        public static string KeepIconVisible {
            get {
                return ResourceManager.GetString("KeepIconVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, Windows will remove the icon from the notification area after a short while. This option attempts to keep it always visible..
        /// </summary>
        public static string KeepIconVisibleToolTip {
            get {
                return ResourceManager.GetString("KeepIconVisibleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain original compose key behaviour.
        /// </summary>
        public static string KeepOriginalKey {
            get {
                return ResourceManager.GetString("KeepOriginalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tells WinCompose to make a best effort to retain the original key’s behaviour. For instance, the Alt-Tab shortcut will still work even if Alt is used as the compose key..
        /// </summary>
        public static string KeepOriginalKeyToolTip {
            get {
                return ResourceManager.GetString("KeepOriginalKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string KeyApps {
            get {
                return ResourceManager.GetString("KeyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard LED.
        /// </summary>
        public static string KeyboardLed {
            get {
                return ResourceManager.GetString("KeyboardLed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, the corresponding keyboard LED will be lit when a compose sequence is in progress..
        /// </summary>
        public static string KeyboardLedToolTip {
            get {
                return ResourceManager.GetString("KeyboardLedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        public static string KeyCapital {
            get {
                return ResourceManager.GetString("KeyCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose.
        /// </summary>
        public static string KeyCompose {
            get {
                return ResourceManager.GetString("KeyCompose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        public static string KeyConvert {
            get {
                return ResourceManager.GetString("KeyConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string KeyDisabled {
            get {
                return ResourceManager.GetString("KeyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string KeyEnd {
            get {
                return ResourceManager.GetString("KeyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string KeyHome {
            get {
                return ResourceManager.GetString("KeyHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string KeyInsert {
            get {
                return ResourceManager.GetString("KeyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Control.
        /// </summary>
        public static string KeyLControl {
            get {
                return ResourceManager.GetString("KeyLControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Alt.
        /// </summary>
        public static string KeyLMenu {
            get {
                return ResourceManager.GetString("KeyLMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Windows.
        /// </summary>
        public static string KeyLWin {
            get {
                return ResourceManager.GetString("KeyLWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-conversion.
        /// </summary>
        public static string KeyNonConvert {
            get {
                return ResourceManager.GetString("KeyNonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Lock.
        /// </summary>
        public static string KeyNumLock {
            get {
                return ResourceManager.GetString("KeyNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string KeyPause {
            get {
                return ResourceManager.GetString("KeyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prt Scrn.
        /// </summary>
        public static string KeyPrint {
            get {
                return ResourceManager.GetString("KeyPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Control.
        /// </summary>
        public static string KeyRControl {
            get {
                return ResourceManager.GetString("KeyRControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string KeyReturn {
            get {
                return ResourceManager.GetString("KeyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Alt.
        /// </summary>
        public static string KeyRMenu {
            get {
                return ResourceManager.GetString("KeyRMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Windows.
        /// </summary>
        public static string KeyRWin {
            get {
                return ResourceManager.GetString("KeyRWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Lock.
        /// </summary>
        public static string KeyScroll {
            get {
                return ResourceManager.GetString("KeyScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string KeySpace {
            get {
                return ResourceManager.GetString("KeySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string KeyTab {
            get {
                return ResourceManager.GetString("KeyTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language that WinCompose uses for the interface. By default the operating system language is used..
        /// </summary>
        public static string LanguageToolTip {
            get {
                return ResourceManager.GetString("LanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is only active while being held down.
        /// </summary>
        public static string MustHoldCapsLock {
            get {
                return ResourceManager.GetString("MustHoldCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releasing the Caps Lock key will immediately disable it, instead of the more standard behaviour of having to press it a second time..
        /// </summary>
        public static string MustHoldCapsLockToolTip {
            get {
                return ResourceManager.GetString("MustHoldCapsLockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCompose needs to be restarted for some changes to take effect..
        /// </summary>
        public static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timeout.
        /// </summary>
        public static string NoTimeout {
            get {
                return ResourceManager.GetString("NoTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options — WinCompose.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        public static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        public static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset timeout.
        /// </summary>
        public static string ResetTimeout {
            get {
                return ResourceManager.GetString("ResetTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with elevated privileges (recommended).
        /// </summary>
        public static string RunElevated {
            get {
                return ResourceManager.GetString("RunElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition will not work in some applications if WinCompose does not run with elevated privileges. This options reduces the chances that this will happen..
        /// </summary>
        public static string RunElevatedToolTip {
            get {
                return ResourceManager.GetString("RunElevatedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filter:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences.
        /// </summary>
        public static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift key disables Caps Lock.
        /// </summary>
        public static string ShiftDisablesCapsLock {
            get {
                return ResourceManager.GetString("ShiftDisablesCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Caps Lock is used as the compose key, the original behaviour of the key becomes unavailable. This feature allows to turn Caps Lock off by pressing the Shift key..
        /// </summary>
        public static string ShiftDisablesCapsLockToolTip {
            get {
                return ResourceManager.GetString("ShiftDisablesCapsLockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options….
        /// </summary>
        public static string ShowOptions {
            get {
                return ResourceManager.GetString("ShowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Sequences….
        /// </summary>
        public static string ShowSequences {
            get {
                return ResourceManager.GetString("ShowSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks.
        /// </summary>
        public static string SpecialThanks {
            get {
                return ResourceManager.GetString("SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to swap the two keys.
        /// </summary>
        public static string SwapOnInvalid {
            get {
                return ResourceManager.GetString("SwapOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to swap the keys of a two-key sequence. For instance, if Compose E A is not a valid sequence, try Compose A E instead..
        /// </summary>
        public static string SwapOnInvalidToolTip {
            get {
                return ResourceManager.GetString("SwapOnInvalidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Typing.
        /// </summary>
        public static string TestTyping {
            get {
                return ResourceManager.GetString("TestTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, any compose sequence will be cancelled after a certain delay if no keyboard activity is detected..
        /// </summary>
        public static string TimeoutToolTip {
            get {
                return ResourceManager.GetString("TimeoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translators {
            get {
                return ResourceManager.GetString("Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCompose v{2} on {0} ({1} sequences).
        /// </summary>
        public static string TrayToolTip {
            get {
                return ResourceManager.GetString("TrayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweaks.
        /// </summary>
        public static string Tweaks {
            get {
                return ResourceManager.GetString("Tweaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode characters.
        /// </summary>
        public static string UnicodeCharacters {
            get {
                return ResourceManager.GetString("UnicodeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Unicode input.
        /// </summary>
        public static string UnicodeInput {
            get {
                return ResourceManager.GetString("UnicodeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Unicode input for all characters, even those with no compose sequence defined. For instance, the following sequence will output character U+1A3F: Compose U 1 A 3 F Enter.
        /// </summary>
        public static string UnicodeInputToolTip {
            get {
                return ResourceManager.GetString("UnicodeInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are available..
        /// </summary>
        public static string UpdatesToolTip {
            get {
                return ResourceManager.GetString("UpdatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use WinCompose emoji sequences.
        /// </summary>
        public static string UseEmojiRules {
            get {
                return ResourceManager.GetString("UseEmojiRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the compose sequences for Emoji provided by the WinCompose author and contributors..
        /// </summary>
        public static string UseEmojiRulesToolTip {
            get {
                return ResourceManager.GetString("UseEmojiRulesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined sequences.
        /// </summary>
        public static string UserDefinedSequences {
            get {
                return ResourceManager.GetString("UserDefinedSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string UserDefinedSequencesEdit {
            get {
                return ResourceManager.GetString("UserDefinedSequencesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string UserDefinedSequencesReload {
            get {
                return ResourceManager.GetString("UserDefinedSequencesReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined macros.
        /// </summary>
        public static string UserMacros {
            get {
                return ResourceManager.GetString("UserMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use sequences from the XCompose project.
        /// </summary>
        public static string UseXComposeRules {
            get {
                return ResourceManager.GetString("UseXComposeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the 1,000 compose sequences from the XCompose opensource project (https://github.com/kragen/xcompose). These sequences may sometimes conflict with the Xorg ones..
        /// </summary>
        public static string UseXComposeRulesToolTip {
            get {
                return ResourceManager.GetString("UseXComposeRulesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use sequences from the Xorg project.
        /// </summary>
        public static string UseXorgRules {
            get {
                return ResourceManager.GetString("UseXorgRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the 3,000 compose sequences from the Xorg project (http://www.x.org/). These are the sequences most commonly found on a standard Linux system..
        /// </summary>
        public static string UseXorgRulesToolTip {
            get {
                return ResourceManager.GetString("UseXorgRulesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        public static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences — WinCompose.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
