//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCompose.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnicodeCategories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnicodeCategories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCompose.Gui.UnicodeCategories", typeof(UnicodeCategories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, close.
        /// </summary>
        public static string ClosePunctuation {
            get {
                return ResourceManager.GetString("ClosePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, connector.
        /// </summary>
        public static string ConnectorPunctuation {
            get {
                return ResourceManager.GetString("ConnectorPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, currency.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, dash.
        /// </summary>
        public static string DashPunctuation {
            get {
                return ResourceManager.GetString("DashPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, decimal digit.
        /// </summary>
        public static string DecimalDigitNumber {
            get {
                return ResourceManager.GetString("DecimalDigitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, enclosing.
        /// </summary>
        public static string EnclosingMark {
            get {
                return ResourceManager.GetString("EnclosingMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, final quote.
        /// </summary>
        public static string FinalQuotePunctuation {
            get {
                return ResourceManager.GetString("FinalQuotePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, initial quote.
        /// </summary>
        public static string InitialQuotePunctuation {
            get {
                return ResourceManager.GetString("InitialQuotePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, letter.
        /// </summary>
        public static string LetterNumber {
            get {
                return ResourceManager.GetString("LetterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, line.
        /// </summary>
        public static string LineSeparator {
            get {
                return ResourceManager.GetString("LineSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, lowercase.
        /// </summary>
        public static string LowercaseLetter {
            get {
                return ResourceManager.GetString("LowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, math.
        /// </summary>
        public static string MathSymbol {
            get {
                return ResourceManager.GetString("MathSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, modifier.
        /// </summary>
        public static string ModifierLetter {
            get {
                return ResourceManager.GetString("ModifierLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, modifier.
        /// </summary>
        public static string ModifierSymbol {
            get {
                return ResourceManager.GetString("ModifierSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, nonspacing.
        /// </summary>
        public static string NonSpacingMark {
            get {
                return ResourceManager.GetString("NonSpacingMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, open.
        /// </summary>
        public static string OpenPunctuation {
            get {
                return ResourceManager.GetString("OpenPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, other.
        /// </summary>
        public static string OtherLetter {
            get {
                return ResourceManager.GetString("OtherLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, not assigned.
        /// </summary>
        public static string OtherNotAssigned {
            get {
                return ResourceManager.GetString("OtherNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, other.
        /// </summary>
        public static string OtherNumber {
            get {
                return ResourceManager.GetString("OtherNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, other.
        /// </summary>
        public static string OtherPunctuation {
            get {
                return ResourceManager.GetString("OtherPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, other.
        /// </summary>
        public static string OtherSymbol {
            get {
                return ResourceManager.GetString("OtherSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, paragraph.
        /// </summary>
        public static string ParagraphSeparator {
            get {
                return ResourceManager.GetString("ParagraphSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, private use.
        /// </summary>
        public static string PrivateUse {
            get {
                return ResourceManager.GetString("PrivateUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, space.
        /// </summary>
        public static string SpaceSeparator {
            get {
                return ResourceManager.GetString("SpaceSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, spacing combining.
        /// </summary>
        public static string SpacingCombiningMark {
            get {
                return ResourceManager.GetString("SpacingCombiningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Surrogate.
        /// </summary>
        public static string Surrogate {
            get {
                return ResourceManager.GetString("Surrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, titlecase.
        /// </summary>
        public static string TitlecaseLetter {
            get {
                return ResourceManager.GetString("TitlecaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, uppercase.
        /// </summary>
        public static string UppercaseLetter {
            get {
                return ResourceManager.GetString("UppercaseLetter", resourceCulture);
            }
        }
    }
}
