//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCompose.unicode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Category {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Category() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCompose.unicode.Category", typeof(Category).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Close.
        /// </summary>
        public static string ClosePunctuation {
            get {
                return ResourceManager.GetString("ClosePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Connector.
        /// </summary>
        public static string ConnectorPunctuation {
            get {
                return ResourceManager.GetString("ConnectorPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Currency.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Dash.
        /// </summary>
        public static string DashPunctuation {
            get {
                return ResourceManager.GetString("DashPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, Decimal Digit.
        /// </summary>
        public static string DecimalDigitNumber {
            get {
                return ResourceManager.GetString("DecimalDigitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, Enclosing.
        /// </summary>
        public static string EnclosingMark {
            get {
                return ResourceManager.GetString("EnclosingMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Final Quote.
        /// </summary>
        public static string FinalQuotePunctuation {
            get {
                return ResourceManager.GetString("FinalQuotePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Initial Quote.
        /// </summary>
        public static string InitialQuotePunctuation {
            get {
                return ResourceManager.GetString("InitialQuotePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, Letter.
        /// </summary>
        public static string LetterNumber {
            get {
                return ResourceManager.GetString("LetterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, Line.
        /// </summary>
        public static string LineSeparator {
            get {
                return ResourceManager.GetString("LineSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Lowercase.
        /// </summary>
        public static string LowercaseLetter {
            get {
                return ResourceManager.GetString("LowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Math.
        /// </summary>
        public static string MathSymbol {
            get {
                return ResourceManager.GetString("MathSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Modifier.
        /// </summary>
        public static string ModifierLetter {
            get {
                return ResourceManager.GetString("ModifierLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Modifier.
        /// </summary>
        public static string ModifierSymbol {
            get {
                return ResourceManager.GetString("ModifierSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, Non-Spacing.
        /// </summary>
        public static string NonSpacingMark {
            get {
                return ResourceManager.GetString("NonSpacingMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Open.
        /// </summary>
        public static string OpenPunctuation {
            get {
                return ResourceManager.GetString("OpenPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Other.
        /// </summary>
        public static string OtherLetter {
            get {
                return ResourceManager.GetString("OtherLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Not Assigned.
        /// </summary>
        public static string OtherNotAssigned {
            get {
                return ResourceManager.GetString("OtherNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, Other.
        /// </summary>
        public static string OtherNumber {
            get {
                return ResourceManager.GetString("OtherNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation, Other.
        /// </summary>
        public static string OtherPunctuation {
            get {
                return ResourceManager.GetString("OtherPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol, Other.
        /// </summary>
        public static string OtherSymbol {
            get {
                return ResourceManager.GetString("OtherSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, Paragraph.
        /// </summary>
        public static string ParagraphSeparator {
            get {
                return ResourceManager.GetString("ParagraphSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Private Use.
        /// </summary>
        public static string PrivateUse {
            get {
                return ResourceManager.GetString("PrivateUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator, Space.
        /// </summary>
        public static string SpaceSeparator {
            get {
                return ResourceManager.GetString("SpaceSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark, Spacing Combining.
        /// </summary>
        public static string SpacingCombiningMark {
            get {
                return ResourceManager.GetString("SpacingCombiningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, Surrogate.
        /// </summary>
        public static string Surrogate {
            get {
                return ResourceManager.GetString("Surrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Titlecase.
        /// </summary>
        public static string TitlecaseLetter {
            get {
                return ResourceManager.GetString("TitlecaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter, Uppercase.
        /// </summary>
        public static string UppercaseLetter {
            get {
                return ResourceManager.GetString("UppercaseLetter", resourceCulture);
            }
        }
    }
}
