//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCompose.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCompose.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCompose.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep on invalid.
        /// </summary>
        public static string BeepOnInvalid {
            get {
                return ResourceManager.GetString("BeepOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case insensitive.
        /// </summary>
        public static string CaseInsensitive {
            get {
                return ResourceManager.GetString("CaseInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose key.
        /// </summary>
        public static string ComposeKey {
            get {
                return ResourceManager.GetString("ComposeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard on invalid.
        /// </summary>
        public static string DiscardOnInvalid {
            get {
                return ResourceManager.GetString("DiscardOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconActive {
            get {
                object obj = ResourceManager.GetObject("IconActive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconDisabled {
            get {
                object obj = ResourceManager.GetObject("IconDisabled", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconEmpty {
            get {
                object obj = ResourceManager.GetObject("IconEmpty", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconNormal {
            get {
                object obj = ResourceManager.GetObject("IconNormal", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In selected categories.
        /// </summary>
        public static string InSelectedCategories {
            get {
                return ResourceManager.GetString("InSelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert zero-width spaces.
        /// </summary>
        public static string InsertZwsp {
            get {
                return ResourceManager.GetString("InsertZwsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep original compose key.
        /// </summary>
        public static string KeepOriginalKey {
            get {
                return ResourceManager.GetString("KeepOriginalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application key.
        /// </summary>
        public static string KeyApps {
            get {
                return ResourceManager.GetString("KeyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        public static string KeyCapital {
            get {
                return ResourceManager.GetString("KeyCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left control.
        /// </summary>
        public static string KeyLControl {
            get {
                return ResourceManager.GetString("KeyLControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Alt.
        /// </summary>
        public static string KeyLMenu {
            get {
                return ResourceManager.GetString("KeyLMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Windows Key.
        /// </summary>
        public static string KeyLWin {
            get {
                return ResourceManager.GetString("KeyLWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumLock.
        /// </summary>
        public static string KeyNumLock {
            get {
                return ResourceManager.GetString("KeyNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string KeyPause {
            get {
                return ResourceManager.GetString("KeyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right control.
        /// </summary>
        public static string KeyRControl {
            get {
                return ResourceManager.GetString("KeyRControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Alt.
        /// </summary>
        public static string KeyRMenu {
            get {
                return ResourceManager.GetString("KeyRMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Windows Key.
        /// </summary>
        public static string KeyRWin {
            get {
                return ResourceManager.GetString("KeyRWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Lock.
        /// </summary>
        public static string KeyScroll {
            get {
                return ResourceManager.GetString("KeyScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings.
        /// </summary>
        public static string Mappings {
            get {
                return ResourceManager.GetString("Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset delay.
        /// </summary>
        public static string ResetDelay {
            get {
                return ResourceManager.GetString("ResetDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences.
        /// </summary>
        public static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sequences….
        /// </summary>
        public static string ShowSequences {
            get {
                return ResourceManager.GetString("ShowSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings….
        /// </summary>
        public static string ShowSettings {
            get {
                return ResourceManager.GetString("ShowSettings", resourceCulture);
            }
        }
    }
}
