//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCompose.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnicodeBlocks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnicodeBlocks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCompose.Properties.UnicodeBlocks", typeof(UnicodeBlocks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Latin.
        /// </summary>
        public static string U0000U007F {
            get {
                return ResourceManager.GetString("U0000U007F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin-1 Supplement.
        /// </summary>
        public static string U0080U00FF {
            get {
                return ResourceManager.GetString("U0080U00FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Extended-A.
        /// </summary>
        public static string U0100U017F {
            get {
                return ResourceManager.GetString("U0100U017F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Extended-B.
        /// </summary>
        public static string U0180U024F {
            get {
                return ResourceManager.GetString("U0180U024F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPA Extensions.
        /// </summary>
        public static string U0250U02AF {
            get {
                return ResourceManager.GetString("U0250U02AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing Modifier Letters.
        /// </summary>
        public static string U02B0U02FF {
            get {
                return ResourceManager.GetString("U02B0U02FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining Diacritical Marks.
        /// </summary>
        public static string U0300U036F {
            get {
                return ResourceManager.GetString("U0300U036F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek and Coptic.
        /// </summary>
        public static string U0370U03FF {
            get {
                return ResourceManager.GetString("U0370U03FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic.
        /// </summary>
        public static string U0400U04FF {
            get {
                return ResourceManager.GetString("U0400U04FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic Supplement.
        /// </summary>
        public static string U0500U052F {
            get {
                return ResourceManager.GetString("U0500U052F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian.
        /// </summary>
        public static string U0530U058F {
            get {
                return ResourceManager.GetString("U0530U058F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string U0590U05FF {
            get {
                return ResourceManager.GetString("U0590U05FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string U0600U06FF {
            get {
                return ResourceManager.GetString("U0600U06FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syriac.
        /// </summary>
        public static string U0700U074F {
            get {
                return ResourceManager.GetString("U0700U074F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Supplement.
        /// </summary>
        public static string U0750U077F {
            get {
                return ResourceManager.GetString("U0750U077F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaana.
        /// </summary>
        public static string U0780U07BF {
            get {
                return ResourceManager.GetString("U0780U07BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NKo.
        /// </summary>
        public static string U07C0U07FF {
            get {
                return ResourceManager.GetString("U07C0U07FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samaritan.
        /// </summary>
        public static string U0800U083F {
            get {
                return ResourceManager.GetString("U0800U083F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandaic.
        /// </summary>
        public static string U0840U085F {
            get {
                return ResourceManager.GetString("U0840U085F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Extended-A.
        /// </summary>
        public static string U08A0U08FF {
            get {
                return ResourceManager.GetString("U08A0U08FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devanagari.
        /// </summary>
        public static string U0900U097F {
            get {
                return ResourceManager.GetString("U0900U097F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengali.
        /// </summary>
        public static string U0980U09FF {
            get {
                return ResourceManager.GetString("U0980U09FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurmukhi.
        /// </summary>
        public static string U0A00U0A7F {
            get {
                return ResourceManager.GetString("U0A00U0A7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarati.
        /// </summary>
        public static string U0A80U0AFF {
            get {
                return ResourceManager.GetString("U0A80U0AFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oriya.
        /// </summary>
        public static string U0B00U0B7F {
            get {
                return ResourceManager.GetString("U0B00U0B7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        public static string U0B80U0BFF {
            get {
                return ResourceManager.GetString("U0B80U0BFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu.
        /// </summary>
        public static string U0C00U0C7F {
            get {
                return ResourceManager.GetString("U0C00U0C7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kannada.
        /// </summary>
        public static string U0C80U0CFF {
            get {
                return ResourceManager.GetString("U0C80U0CFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malayalam.
        /// </summary>
        public static string U0D00U0D7F {
            get {
                return ResourceManager.GetString("U0D00U0D7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhala.
        /// </summary>
        public static string U0D80U0DFF {
            get {
                return ResourceManager.GetString("U0D80U0DFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string U0E00U0E7F {
            get {
                return ResourceManager.GetString("U0E00U0E7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        public static string U0E80U0EFF {
            get {
                return ResourceManager.GetString("U0E80U0EFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibetan.
        /// </summary>
        public static string U0F00U0FFF {
            get {
                return ResourceManager.GetString("U0F00U0FFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementary Private Use Area-B.
        /// </summary>
        public static string U100000U10FFFF {
            get {
                return ResourceManager.GetString("U100000U10FFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear B Syllabary.
        /// </summary>
        public static string U10000U1007F {
            get {
                return ResourceManager.GetString("U10000U1007F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar.
        /// </summary>
        public static string U1000U109F {
            get {
                return ResourceManager.GetString("U1000U109F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear B Ideograms.
        /// </summary>
        public static string U10080U100FF {
            get {
                return ResourceManager.GetString("U10080U100FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aegean Numbers.
        /// </summary>
        public static string U10100U1013F {
            get {
                return ResourceManager.GetString("U10100U1013F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient Greek Numbers.
        /// </summary>
        public static string U10140U1018F {
            get {
                return ResourceManager.GetString("U10140U1018F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient Symbols.
        /// </summary>
        public static string U10190U101CF {
            get {
                return ResourceManager.GetString("U10190U101CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaistos Disc.
        /// </summary>
        public static string U101D0U101FF {
            get {
                return ResourceManager.GetString("U101D0U101FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lycian.
        /// </summary>
        public static string U10280U1029F {
            get {
                return ResourceManager.GetString("U10280U1029F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carian.
        /// </summary>
        public static string U102A0U102DF {
            get {
                return ResourceManager.GetString("U102A0U102DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coptic Epact Numbers.
        /// </summary>
        public static string U102E0U102FF {
            get {
                return ResourceManager.GetString("U102E0U102FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Italic.
        /// </summary>
        public static string U10300U1032F {
            get {
                return ResourceManager.GetString("U10300U1032F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic.
        /// </summary>
        public static string U10330U1034F {
            get {
                return ResourceManager.GetString("U10330U1034F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Permic.
        /// </summary>
        public static string U10350U1037F {
            get {
                return ResourceManager.GetString("U10350U1037F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugaritic.
        /// </summary>
        public static string U10380U1039F {
            get {
                return ResourceManager.GetString("U10380U1039F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Persian.
        /// </summary>
        public static string U103A0U103DF {
            get {
                return ResourceManager.GetString("U103A0U103DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseret.
        /// </summary>
        public static string U10400U1044F {
            get {
                return ResourceManager.GetString("U10400U1044F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shavian.
        /// </summary>
        public static string U10450U1047F {
            get {
                return ResourceManager.GetString("U10450U1047F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osmanya.
        /// </summary>
        public static string U10480U104AF {
            get {
                return ResourceManager.GetString("U10480U104AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elbasan.
        /// </summary>
        public static string U10500U1052F {
            get {
                return ResourceManager.GetString("U10500U1052F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caucasian Albanian.
        /// </summary>
        public static string U10530U1056F {
            get {
                return ResourceManager.GetString("U10530U1056F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear A.
        /// </summary>
        public static string U10600U1077F {
            get {
                return ResourceManager.GetString("U10600U1077F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cypriot Syllabary.
        /// </summary>
        public static string U10800U1083F {
            get {
                return ResourceManager.GetString("U10800U1083F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial Aramaic.
        /// </summary>
        public static string U10840U1085F {
            get {
                return ResourceManager.GetString("U10840U1085F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palmyrene.
        /// </summary>
        public static string U10860U1087F {
            get {
                return ResourceManager.GetString("U10860U1087F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabataean.
        /// </summary>
        public static string U10880U108AF {
            get {
                return ResourceManager.GetString("U10880U108AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoenician.
        /// </summary>
        public static string U10900U1091F {
            get {
                return ResourceManager.GetString("U10900U1091F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lydian.
        /// </summary>
        public static string U10920U1093F {
            get {
                return ResourceManager.GetString("U10920U1093F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meroitic Hieroglyphs.
        /// </summary>
        public static string U10980U1099F {
            get {
                return ResourceManager.GetString("U10980U1099F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meroitic Cursive.
        /// </summary>
        public static string U109A0U109FF {
            get {
                return ResourceManager.GetString("U109A0U109FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kharoshthi.
        /// </summary>
        public static string U10A00U10A5F {
            get {
                return ResourceManager.GetString("U10A00U10A5F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string U10A0U10FF {
            get {
                return ResourceManager.GetString("U10A0U10FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old South Arabian.
        /// </summary>
        public static string U10A60U10A7F {
            get {
                return ResourceManager.GetString("U10A60U10A7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old North Arabian.
        /// </summary>
        public static string U10A80U10A9F {
            get {
                return ResourceManager.GetString("U10A80U10A9F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manichaean.
        /// </summary>
        public static string U10AC0U10AFF {
            get {
                return ResourceManager.GetString("U10AC0U10AFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avestan.
        /// </summary>
        public static string U10B00U10B3F {
            get {
                return ResourceManager.GetString("U10B00U10B3F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscriptional Parthian.
        /// </summary>
        public static string U10B40U10B5F {
            get {
                return ResourceManager.GetString("U10B40U10B5F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscriptional Pahlavi.
        /// </summary>
        public static string U10B60U10B7F {
            get {
                return ResourceManager.GetString("U10B60U10B7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psalter Pahlavi.
        /// </summary>
        public static string U10B80U10BAF {
            get {
                return ResourceManager.GetString("U10B80U10BAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Turkic.
        /// </summary>
        public static string U10C00U10C4F {
            get {
                return ResourceManager.GetString("U10C00U10C4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumi Numeral Symbols.
        /// </summary>
        public static string U10E60U10E7F {
            get {
                return ResourceManager.GetString("U10E60U10E7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brahmi.
        /// </summary>
        public static string U11000U1107F {
            get {
                return ResourceManager.GetString("U11000U1107F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangul Jamo.
        /// </summary>
        public static string U1100U11FF {
            get {
                return ResourceManager.GetString("U1100U11FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaithi.
        /// </summary>
        public static string U11080U110CF {
            get {
                return ResourceManager.GetString("U11080U110CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sora Sompeng.
        /// </summary>
        public static string U110D0U110FF {
            get {
                return ResourceManager.GetString("U110D0U110FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chakma.
        /// </summary>
        public static string U11100U1114F {
            get {
                return ResourceManager.GetString("U11100U1114F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahajani.
        /// </summary>
        public static string U11150U1117F {
            get {
                return ResourceManager.GetString("U11150U1117F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharada.
        /// </summary>
        public static string U11180U111DF {
            get {
                return ResourceManager.GetString("U11180U111DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhala Archaic Numbers.
        /// </summary>
        public static string U111E0U111FF {
            get {
                return ResourceManager.GetString("U111E0U111FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khojki.
        /// </summary>
        public static string U11200U1124F {
            get {
                return ResourceManager.GetString("U11200U1124F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khudawadi.
        /// </summary>
        public static string U112B0U112FF {
            get {
                return ResourceManager.GetString("U112B0U112FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grantha.
        /// </summary>
        public static string U11300U1137F {
            get {
                return ResourceManager.GetString("U11300U1137F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tirhuta.
        /// </summary>
        public static string U11480U114DF {
            get {
                return ResourceManager.GetString("U11480U114DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siddham.
        /// </summary>
        public static string U11580U115FF {
            get {
                return ResourceManager.GetString("U11580U115FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modi.
        /// </summary>
        public static string U11600U1165F {
            get {
                return ResourceManager.GetString("U11600U1165F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takri.
        /// </summary>
        public static string U11680U116CF {
            get {
                return ResourceManager.GetString("U11680U116CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warang Citi.
        /// </summary>
        public static string U118A0U118FF {
            get {
                return ResourceManager.GetString("U118A0U118FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pau Cin Hau.
        /// </summary>
        public static string U11AC0U11AFF {
            get {
                return ResourceManager.GetString("U11AC0U11AFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuneiform.
        /// </summary>
        public static string U12000U123FF {
            get {
                return ResourceManager.GetString("U12000U123FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopic.
        /// </summary>
        public static string U1200U137F {
            get {
                return ResourceManager.GetString("U1200U137F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuneiform Numbers and Punctuation.
        /// </summary>
        public static string U12400U1247F {
            get {
                return ResourceManager.GetString("U12400U1247F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian Hieroglyphs.
        /// </summary>
        public static string U13000U1342F {
            get {
                return ResourceManager.GetString("U13000U1342F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopic Supplement.
        /// </summary>
        public static string U1380U139F {
            get {
                return ResourceManager.GetString("U1380U139F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherokee.
        /// </summary>
        public static string U13A0U13FF {
            get {
                return ResourceManager.GetString("U13A0U13FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Canadian Aboriginal Syllabics.
        /// </summary>
        public static string U1400U167F {
            get {
                return ResourceManager.GetString("U1400U167F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bamum Supplement.
        /// </summary>
        public static string U16800U16A3F {
            get {
                return ResourceManager.GetString("U16800U16A3F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogham.
        /// </summary>
        public static string U1680U169F {
            get {
                return ResourceManager.GetString("U1680U169F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runic.
        /// </summary>
        public static string U16A0U16FF {
            get {
                return ResourceManager.GetString("U16A0U16FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mro.
        /// </summary>
        public static string U16A40U16A6F {
            get {
                return ResourceManager.GetString("U16A40U16A6F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bassa Vah.
        /// </summary>
        public static string U16AD0U16AFF {
            get {
                return ResourceManager.GetString("U16AD0U16AFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahawh Hmong.
        /// </summary>
        public static string U16B00U16B8F {
            get {
                return ResourceManager.GetString("U16B00U16B8F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miao.
        /// </summary>
        public static string U16F00U16F9F {
            get {
                return ResourceManager.GetString("U16F00U16F9F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagalog.
        /// </summary>
        public static string U1700U171F {
            get {
                return ResourceManager.GetString("U1700U171F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanunoo.
        /// </summary>
        public static string U1720U173F {
            get {
                return ResourceManager.GetString("U1720U173F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buhid.
        /// </summary>
        public static string U1740U175F {
            get {
                return ResourceManager.GetString("U1740U175F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagbanwa.
        /// </summary>
        public static string U1760U177F {
            get {
                return ResourceManager.GetString("U1760U177F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string U1780U17FF {
            get {
                return ResourceManager.GetString("U1780U17FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string U1800U18AF {
            get {
                return ResourceManager.GetString("U1800U18AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Canadian Aboriginal Syllabics Extended.
        /// </summary>
        public static string U18B0U18FF {
            get {
                return ResourceManager.GetString("U18B0U18FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limbu.
        /// </summary>
        public static string U1900U194F {
            get {
                return ResourceManager.GetString("U1900U194F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai Le.
        /// </summary>
        public static string U1950U197F {
            get {
                return ResourceManager.GetString("U1950U197F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tai Lue.
        /// </summary>
        public static string U1980U19DF {
            get {
                return ResourceManager.GetString("U1980U19DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer Symbols.
        /// </summary>
        public static string U19E0U19FF {
            get {
                return ResourceManager.GetString("U19E0U19FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buginese.
        /// </summary>
        public static string U1A00U1A1F {
            get {
                return ResourceManager.GetString("U1A00U1A1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai Tham.
        /// </summary>
        public static string U1A20U1AAF {
            get {
                return ResourceManager.GetString("U1A20U1AAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining Diacritical Marks Extended.
        /// </summary>
        public static string U1AB0U1AFF {
            get {
                return ResourceManager.GetString("U1AB0U1AFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kana Supplement.
        /// </summary>
        public static string U1B000U1B0FF {
            get {
                return ResourceManager.GetString("U1B000U1B0FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balinese.
        /// </summary>
        public static string U1B00U1B7F {
            get {
                return ResourceManager.GetString("U1B00U1B7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sundanese.
        /// </summary>
        public static string U1B80U1BBF {
            get {
                return ResourceManager.GetString("U1B80U1BBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duployan.
        /// </summary>
        public static string U1BC00U1BC9F {
            get {
                return ResourceManager.GetString("U1BC00U1BC9F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batak.
        /// </summary>
        public static string U1BC0U1BFF {
            get {
                return ResourceManager.GetString("U1BC0U1BFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorthand Format Controls.
        /// </summary>
        public static string U1BCA0U1BCAF {
            get {
                return ResourceManager.GetString("U1BCA0U1BCAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lepcha.
        /// </summary>
        public static string U1C00U1C4F {
            get {
                return ResourceManager.GetString("U1C00U1C4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ol Chiki.
        /// </summary>
        public static string U1C50U1C7F {
            get {
                return ResourceManager.GetString("U1C50U1C7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sundanese Supplement.
        /// </summary>
        public static string U1CC0U1CCF {
            get {
                return ResourceManager.GetString("U1CC0U1CCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedic Extensions.
        /// </summary>
        public static string U1CD0U1CFF {
            get {
                return ResourceManager.GetString("U1CD0U1CFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byzantine Musical Symbols.
        /// </summary>
        public static string U1D000U1D0FF {
            get {
                return ResourceManager.GetString("U1D000U1D0FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Extensions.
        /// </summary>
        public static string U1D00U1D7F {
            get {
                return ResourceManager.GetString("U1D00U1D7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Symbols.
        /// </summary>
        public static string U1D100U1D1FF {
            get {
                return ResourceManager.GetString("U1D100U1D1FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient Greek Musical Notation.
        /// </summary>
        public static string U1D200U1D24F {
            get {
                return ResourceManager.GetString("U1D200U1D24F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai Xuan Jing Symbols.
        /// </summary>
        public static string U1D300U1D35F {
            get {
                return ResourceManager.GetString("U1D300U1D35F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting Rod Numerals.
        /// </summary>
        public static string U1D360U1D37F {
            get {
                return ResourceManager.GetString("U1D360U1D37F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematical Alphanumeric Symbols.
        /// </summary>
        public static string U1D400U1D7FF {
            get {
                return ResourceManager.GetString("U1D400U1D7FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Extensions Supplement.
        /// </summary>
        public static string U1D80U1DBF {
            get {
                return ResourceManager.GetString("U1D80U1DBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining Diacritical Marks Supplement.
        /// </summary>
        public static string U1DC0U1DFF {
            get {
                return ResourceManager.GetString("U1DC0U1DFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Extended Additional.
        /// </summary>
        public static string U1E00U1EFF {
            get {
                return ResourceManager.GetString("U1E00U1EFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mende Kikakui.
        /// </summary>
        public static string U1E800U1E8DF {
            get {
                return ResourceManager.GetString("U1E800U1E8DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Mathematical Alphabetic Symbols.
        /// </summary>
        public static string U1EE00U1EEFF {
            get {
                return ResourceManager.GetString("U1EE00U1EEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahjong Tiles.
        /// </summary>
        public static string U1F000U1F02F {
            get {
                return ResourceManager.GetString("U1F000U1F02F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek Extended.
        /// </summary>
        public static string U1F00U1FFF {
            get {
                return ResourceManager.GetString("U1F00U1FFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Tiles.
        /// </summary>
        public static string U1F030U1F09F {
            get {
                return ResourceManager.GetString("U1F030U1F09F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing Cards.
        /// </summary>
        public static string U1F0A0U1F0FF {
            get {
                return ResourceManager.GetString("U1F0A0U1F0FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclosed Alphanumeric Supplement.
        /// </summary>
        public static string U1F100U1F1FF {
            get {
                return ResourceManager.GetString("U1F100U1F1FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclosed Ideographic Supplement.
        /// </summary>
        public static string U1F200U1F2FF {
            get {
                return ResourceManager.GetString("U1F200U1F2FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Symbols and Pictographs.
        /// </summary>
        public static string U1F300U1F5FF {
            get {
                return ResourceManager.GetString("U1F300U1F5FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoticons.
        /// </summary>
        public static string U1F600U1F64F {
            get {
                return ResourceManager.GetString("U1F600U1F64F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornamental Dingbats.
        /// </summary>
        public static string U1F650U1F67F {
            get {
                return ResourceManager.GetString("U1F650U1F67F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport and Map Symbols.
        /// </summary>
        public static string U1F680U1F6FF {
            get {
                return ResourceManager.GetString("U1F680U1F6FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemical Symbols.
        /// </summary>
        public static string U1F700U1F77F {
            get {
                return ResourceManager.GetString("U1F700U1F77F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Shapes Extended.
        /// </summary>
        public static string U1F780U1F7FF {
            get {
                return ResourceManager.GetString("U1F780U1F7FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Arrows-C.
        /// </summary>
        public static string U1F800U1F8FF {
            get {
                return ResourceManager.GetString("U1F800U1F8FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Unified Ideographs Extension B.
        /// </summary>
        public static string U20000U2A6DF {
            get {
                return ResourceManager.GetString("U20000U2A6DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Punctuation.
        /// </summary>
        public static string U2000U206F {
            get {
                return ResourceManager.GetString("U2000U206F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscripts and Subscripts.
        /// </summary>
        public static string U2070U209F {
            get {
                return ResourceManager.GetString("U2070U209F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbols.
        /// </summary>
        public static string U20A0U20CF {
            get {
                return ResourceManager.GetString("U20A0U20CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining Diacritical Marks for Symbols.
        /// </summary>
        public static string U20D0U20FF {
            get {
                return ResourceManager.GetString("U20D0U20FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letterlike Symbols.
        /// </summary>
        public static string U2100U214F {
            get {
                return ResourceManager.GetString("U2100U214F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Forms.
        /// </summary>
        public static string U2150U218F {
            get {
                return ResourceManager.GetString("U2150U218F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrows.
        /// </summary>
        public static string U2190U21FF {
            get {
                return ResourceManager.GetString("U2190U21FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematical Operators.
        /// </summary>
        public static string U2200U22FF {
            get {
                return ResourceManager.GetString("U2200U22FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Technical.
        /// </summary>
        public static string U2300U23FF {
            get {
                return ResourceManager.GetString("U2300U23FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Pictures.
        /// </summary>
        public static string U2400U243F {
            get {
                return ResourceManager.GetString("U2400U243F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Character Recognition.
        /// </summary>
        public static string U2440U245F {
            get {
                return ResourceManager.GetString("U2440U245F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclosed Alphanumerics.
        /// </summary>
        public static string U2460U24FF {
            get {
                return ResourceManager.GetString("U2460U24FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Drawing.
        /// </summary>
        public static string U2500U257F {
            get {
                return ResourceManager.GetString("U2500U257F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Elements.
        /// </summary>
        public static string U2580U259F {
            get {
                return ResourceManager.GetString("U2580U259F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Shapes.
        /// </summary>
        public static string U25A0U25FF {
            get {
                return ResourceManager.GetString("U25A0U25FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Symbols.
        /// </summary>
        public static string U2600U26FF {
            get {
                return ResourceManager.GetString("U2600U26FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dingbats.
        /// </summary>
        public static string U2700U27BF {
            get {
                return ResourceManager.GetString("U2700U27BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Mathematical Symbols-A.
        /// </summary>
        public static string U27C0U27EF {
            get {
                return ResourceManager.GetString("U27C0U27EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Arrows-A.
        /// </summary>
        public static string U27F0U27FF {
            get {
                return ResourceManager.GetString("U27F0U27FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille Patterns.
        /// </summary>
        public static string U2800U28FF {
            get {
                return ResourceManager.GetString("U2800U28FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Arrows-B.
        /// </summary>
        public static string U2900U297F {
            get {
                return ResourceManager.GetString("U2900U297F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Mathematical Symbols-B.
        /// </summary>
        public static string U2980U29FF {
            get {
                return ResourceManager.GetString("U2980U29FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Mathematical Operators.
        /// </summary>
        public static string U2A00U2AFF {
            get {
                return ResourceManager.GetString("U2A00U2AFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Unified Ideographs Extension C.
        /// </summary>
        public static string U2A700U2B73F {
            get {
                return ResourceManager.GetString("U2A700U2B73F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Symbols and Arrows.
        /// </summary>
        public static string U2B00U2BFF {
            get {
                return ResourceManager.GetString("U2B00U2BFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Unified Ideographs Extension D.
        /// </summary>
        public static string U2B740U2B81F {
            get {
                return ResourceManager.GetString("U2B740U2B81F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glagolitic.
        /// </summary>
        public static string U2C00U2C5F {
            get {
                return ResourceManager.GetString("U2C00U2C5F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Extended-C.
        /// </summary>
        public static string U2C60U2C7F {
            get {
                return ResourceManager.GetString("U2C60U2C7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coptic.
        /// </summary>
        public static string U2C80U2CFF {
            get {
                return ResourceManager.GetString("U2C80U2CFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian Supplement.
        /// </summary>
        public static string U2D00U2D2F {
            get {
                return ResourceManager.GetString("U2D00U2D2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tifinagh.
        /// </summary>
        public static string U2D30U2D7F {
            get {
                return ResourceManager.GetString("U2D30U2D7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopic Extended.
        /// </summary>
        public static string U2D80U2DDF {
            get {
                return ResourceManager.GetString("U2D80U2DDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic Extended-A.
        /// </summary>
        public static string U2DE0U2DFF {
            get {
                return ResourceManager.GetString("U2DE0U2DFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Punctuation.
        /// </summary>
        public static string U2E00U2E7F {
            get {
                return ResourceManager.GetString("U2E00U2E7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Radicals Supplement.
        /// </summary>
        public static string U2E80U2EFF {
            get {
                return ResourceManager.GetString("U2E80U2EFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kangxi Radicals.
        /// </summary>
        public static string U2F00U2FDF {
            get {
                return ResourceManager.GetString("U2F00U2FDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Compatibility Ideographs Supplement.
        /// </summary>
        public static string U2F800U2FA1F {
            get {
                return ResourceManager.GetString("U2F800U2FA1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideographic Description Characters.
        /// </summary>
        public static string U2FF0U2FFF {
            get {
                return ResourceManager.GetString("U2FF0U2FFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Symbols and Punctuation.
        /// </summary>
        public static string U3000U303F {
            get {
                return ResourceManager.GetString("U3000U303F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiragana.
        /// </summary>
        public static string U3040U309F {
            get {
                return ResourceManager.GetString("U3040U309F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katakana.
        /// </summary>
        public static string U30A0U30FF {
            get {
                return ResourceManager.GetString("U30A0U30FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bopomofo.
        /// </summary>
        public static string U3100U312F {
            get {
                return ResourceManager.GetString("U3100U312F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangul Compatibility Jamo.
        /// </summary>
        public static string U3130U318F {
            get {
                return ResourceManager.GetString("U3130U318F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanbun.
        /// </summary>
        public static string U3190U319F {
            get {
                return ResourceManager.GetString("U3190U319F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bopomofo Extended.
        /// </summary>
        public static string U31A0U31BF {
            get {
                return ResourceManager.GetString("U31A0U31BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Strokes.
        /// </summary>
        public static string U31C0U31EF {
            get {
                return ResourceManager.GetString("U31C0U31EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katakana Phonetic Extensions.
        /// </summary>
        public static string U31F0U31FF {
            get {
                return ResourceManager.GetString("U31F0U31FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclosed CJK Letters and Months.
        /// </summary>
        public static string U3200U32FF {
            get {
                return ResourceManager.GetString("U3200U32FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Compatibility.
        /// </summary>
        public static string U3300U33FF {
            get {
                return ResourceManager.GetString("U3300U33FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Unified Ideographs Extension A.
        /// </summary>
        public static string U3400U4DBF {
            get {
                return ResourceManager.GetString("U3400U4DBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yijing Hexagram Symbols.
        /// </summary>
        public static string U4DC0U4DFF {
            get {
                return ResourceManager.GetString("U4DC0U4DFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Unified Ideographs.
        /// </summary>
        public static string U4E00U9FFF {
            get {
                return ResourceManager.GetString("U4E00U9FFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yi Syllables.
        /// </summary>
        public static string UA000UA48F {
            get {
                return ResourceManager.GetString("UA000UA48F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yi Radicals.
        /// </summary>
        public static string UA490UA4CF {
            get {
                return ResourceManager.GetString("UA490UA4CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisu.
        /// </summary>
        public static string UA4D0UA4FF {
            get {
                return ResourceManager.GetString("UA4D0UA4FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai.
        /// </summary>
        public static string UA500UA63F {
            get {
                return ResourceManager.GetString("UA500UA63F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic Extended-B.
        /// </summary>
        public static string UA640UA69F {
            get {
                return ResourceManager.GetString("UA640UA69F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bamum.
        /// </summary>
        public static string UA6A0UA6FF {
            get {
                return ResourceManager.GetString("UA6A0UA6FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Tone Letters.
        /// </summary>
        public static string UA700UA71F {
            get {
                return ResourceManager.GetString("UA700UA71F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Extended-D.
        /// </summary>
        public static string UA720UA7FF {
            get {
                return ResourceManager.GetString("UA720UA7FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syloti Nagri.
        /// </summary>
        public static string UA800UA82F {
            get {
                return ResourceManager.GetString("UA800UA82F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Indic Number Forms.
        /// </summary>
        public static string UA830UA83F {
            get {
                return ResourceManager.GetString("UA830UA83F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phags-pa.
        /// </summary>
        public static string UA840UA87F {
            get {
                return ResourceManager.GetString("UA840UA87F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saurashtra.
        /// </summary>
        public static string UA880UA8DF {
            get {
                return ResourceManager.GetString("UA880UA8DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devanagari Extended.
        /// </summary>
        public static string UA8E0UA8FF {
            get {
                return ResourceManager.GetString("UA8E0UA8FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayah Li.
        /// </summary>
        public static string UA900UA92F {
            get {
                return ResourceManager.GetString("UA900UA92F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejang.
        /// </summary>
        public static string UA930UA95F {
            get {
                return ResourceManager.GetString("UA930UA95F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangul Jamo Extended-A.
        /// </summary>
        public static string UA960UA97F {
            get {
                return ResourceManager.GetString("UA960UA97F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javanese.
        /// </summary>
        public static string UA980UA9DF {
            get {
                return ResourceManager.GetString("UA980UA9DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar Extended-B.
        /// </summary>
        public static string UA9E0UA9FF {
            get {
                return ResourceManager.GetString("UA9E0UA9FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cham.
        /// </summary>
        public static string UAA00UAA5F {
            get {
                return ResourceManager.GetString("UAA00UAA5F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar Extended-A.
        /// </summary>
        public static string UAA60UAA7F {
            get {
                return ResourceManager.GetString("UAA60UAA7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai Viet.
        /// </summary>
        public static string UAA80UAADF {
            get {
                return ResourceManager.GetString("UAA80UAADF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetei Mayek Extensions.
        /// </summary>
        public static string UAAE0UAAFF {
            get {
                return ResourceManager.GetString("UAAE0UAAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopic Extended-A.
        /// </summary>
        public static string UAB00UAB2F {
            get {
                return ResourceManager.GetString("UAB00UAB2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin Extended-E.
        /// </summary>
        public static string UAB30UAB6F {
            get {
                return ResourceManager.GetString("UAB30UAB6F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetei Mayek.
        /// </summary>
        public static string UABC0UABFF {
            get {
                return ResourceManager.GetString("UABC0UABFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangul Syllables.
        /// </summary>
        public static string UAC00UD7AF {
            get {
                return ResourceManager.GetString("UAC00UD7AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangul Jamo Extended-B.
        /// </summary>
        public static string UD7B0UD7FF {
            get {
                return ResourceManager.GetString("UD7B0UD7FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Surrogates.
        /// </summary>
        public static string UD800UDB7F {
            get {
                return ResourceManager.GetString("UD800UDB7F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Private Use Surrogates.
        /// </summary>
        public static string UDB80UDBFF {
            get {
                return ResourceManager.GetString("UDB80UDBFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Surrogates.
        /// </summary>
        public static string UDC00UDFFF {
            get {
                return ResourceManager.GetString("UDC00UDFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string UE0000UE007F {
            get {
                return ResourceManager.GetString("UE0000UE007F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Use Area.
        /// </summary>
        public static string UE000UF8FF {
            get {
                return ResourceManager.GetString("UE000UF8FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation Selectors Supplement.
        /// </summary>
        public static string UE0100UE01EF {
            get {
                return ResourceManager.GetString("UE0100UE01EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplementary Private Use Area-A.
        /// </summary>
        public static string UF0000UFFFFF {
            get {
                return ResourceManager.GetString("UF0000UFFFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Compatibility Ideographs.
        /// </summary>
        public static string UF900UFAFF {
            get {
                return ResourceManager.GetString("UF900UFAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetic Presentation Forms.
        /// </summary>
        public static string UFB00UFB4F {
            get {
                return ResourceManager.GetString("UFB00UFB4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Presentation Forms-A.
        /// </summary>
        public static string UFB50UFDFF {
            get {
                return ResourceManager.GetString("UFB50UFDFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation Selectors.
        /// </summary>
        public static string UFE00UFE0F {
            get {
                return ResourceManager.GetString("UFE00UFE0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Forms.
        /// </summary>
        public static string UFE10UFE1F {
            get {
                return ResourceManager.GetString("UFE10UFE1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining Half Marks.
        /// </summary>
        public static string UFE20UFE2F {
            get {
                return ResourceManager.GetString("UFE20UFE2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJK Compatibility Forms.
        /// </summary>
        public static string UFE30UFE4F {
            get {
                return ResourceManager.GetString("UFE30UFE4F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Form Variants.
        /// </summary>
        public static string UFE50UFE6F {
            get {
                return ResourceManager.GetString("UFE50UFE6F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Presentation Forms-B.
        /// </summary>
        public static string UFE70UFEFF {
            get {
                return ResourceManager.GetString("UFE70UFEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfwidth and Fullwidth Forms.
        /// </summary>
        public static string UFF00UFFEF {
            get {
                return ResourceManager.GetString("UFF00UFFEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        public static string UFFF0UFFFF {
            get {
                return ResourceManager.GetString("UFFF0UFFFF", resourceCulture);
            }
        }
    }
}
